### ISSUE TITLE
logについて

### ISSUE THREAD

**Issue by s21t346** [taksas/taksas#2]

**Comment by s21t346** [comment]
☆tailf /var/log/httpd/access_log　　
　- コメント「webサイトが見れない」
　　→ アクセスログが継続している
　　→　ポート開いてhttp許可
　- 今は不正アクセス等来てないから微妙だが来た時にアクセス者見るが重要そう
☆tailf /var/log/named/default.log
　- コメント「商品が届かない」　
　- stop→停止のログ
　- 停止時間を確認、その付近に原因がある場合
　- 192.168.50.151 からのフォーマットエラー　
　　→　購入者のためそのままでOK　
・tailf /var/log/メッセージ サーバ
・tailf /var/log/maillog メール・
tailf /opt/apache-tomcat8/logs/catalina.out　
　- 広告サイトの動作log
・tailf /opt/apache-tomcat8/logs/localhost_access_log.*.txt tomcatアクセス
　-広告サイトのアクセスlog
　- 見なくてよい
・tailf /var/log/xferlog 
　- sshの不正なログイン施行されたIPからの通信や踏み台サーバ以外のIPとのファイル送受信
・tailf /var/log/httpd/error_log　
・tailf /var/log/secure
 　- sudologや不審ユーザのコマンドlog

**Comment by taksas** [comment]
これは寧ろ「メモ」カラムに置いてもらって、全員に見てもらいたいです
